### ISSUE TITLE
Bug: Allow fields are not being respected when the input object does not contain the corresponding parameter.

### ISSUE THREAD

**Issue by MatiasDuhalde** [tada5hi/rapiq#261]
### Versions
- Node: v19.9.0
- OS: Arch Linux x86_64 6.3.1-arch2-1
- Rapiq: 0.8.0

### Reproduction

I implemented a minimal example in [CodeSandbox](https://codesandbox.io/p/sandbox/optimistic-germain-odxclc?file=%2Fsrc%2Findex.ts%3A3%2C23). Here's that same code:

```typescript
import { ParseOptions, parseQuery } from "rapiq";

class User {
  firstName: string;
  lastName: string;
  password: string;
}

const options: ParseOptions<User> = {
  defaultPath: "user",
  fields: { allowed: ["firstName", "lastName"] },
};

const parsed1 = parseQuery<User>({}, options);

console.log(parsed1);
// unexpected behavior
// output:   { defaultPath: 'user' }
// expected: { defaultPath: 'user', fields: [ { key: 'firstName', path: 'user' }, { key: 'lastName', path: 'user' } ] }

const parsed2 = parseQuery<User>(
  {
    fields: ["firstName", "password"],
  },
  options
);

console.log(parsed2);
// correct
// output:   { defaultPath: 'user', fields: [ { key: 'firstName', path: 'user' } ] }
// expected: { defaultPath: 'user', fields: [ { key: 'firstName', path: 'user' } ] }
```

The returned object does not contain the `fields` attribute when the input is an empty object, even though the allowed fields are being limited in the options object.

If we then pass this object to TypeORM (by using the methods available in `typeorm-extension`), it will return all  the fields of the entity, even those we didn't allow (`password` in my example), since TypeORM doesn't have knowledge of the options we specified to `rapiq`.

<details open>
<summary>Additional Details</summary>
</details>

### Steps to reproduce

See previous section.

### What is Expected?

Not sure if this is intended behavior or not. But I expected to limit the fields to those in the "allowed" array by default. Of course, this can be handled by ensuring the object is not empty before passing the object to the parsing function, but I would expect the library to do this automatically if there are restrictions in the options object.

### What is actually happening?

The "allow" fields are not being respected . I think is related to the fact that in `parseQuery`, the function verifies if the corresponding parameter in the input is truthy or not. Since the attribute turns out to be `undefined`, it never calls `parseQueryParameter`. I can try and submit a PR if the behavior if it doesn't turn out to be too complicated.

**Comment by MatiasDuhalde** [comment]
Hey @tada5hi :wave: Thanks for the response!

I started rethinking this issue and tinkering with the edge cases, and came to the conclusion that making a decision might depend on the objective of `rapiq` as a whole.

When making an empty request (say, GET /users without any query params), Express sets `req.query` as `{}` by default. Usually, when making a request without customizing it with parameters, it means we'll just assume whatever default the server might have preconfigured. But who/where should we define this defaults? Is it one of the goals of this library? I think `rapiq` has all the potential to do so! But for that to work, I also consider it should work out of the box for the most popular use cases, like handling Express' empty `req.query`. Other libraries, namely Koa and Fastify, also set `req.query` as an empty object by default.

With the current behavior, undefined query parameters skip parsing, and defining them as empty lists forces parsing. But what does it really mean to have an empty list?
```typescript
const emptyInput: ParseInput = {
  fields: [],
  filters: [],
  relations: [],
  sort: [],
};
```
For filters, relations, and sort it might be clear: we want an unfiltered query, no relations, and we don't care about the order. But for the fields, an empty list might mean we want a response with no fields, but that doesn't make much sense. The current behavior results in the intersection of allows and default if both are defined, the union if only one is defined, and all fields if none are.

So, in short, I think the parameter should parse if either `allows` or `default` is defined. And if default is not defined, it should be set to `allows`. Again, if I pass an empty object and I configure the parser to have some predefined allowed values (even if there's no default), I would expect the query to be limited to those "allowed" values.

I might be wrong for the rest of the parameters, but that would mean an empty input `{}` should have the same behavior as the object with empty arrays, and maybe rethinking the meaning of an empty array, specifically for the `fields` property. This might of course break any kind of backwards compatibility for those edge cases, so I apologize if what I'm proposing seems to stray too much from `rapiq`'s original use case.

I tested some edge cases in the same [CodeSandbox](https://codesandbox.io/p/sandbox/odxclc), and added some comments describing the actual output vs what I would expect (of course, the expect part is nothing more that my personal feeling as a user of this tool, opinions might differ). Here's the code:

```typescript
Hey @tada5hi :wave: Thanks for the response!

I started rethinking this issue and tinkering with the edge cases, and came to the conclusion that making a decision might depend on the objective of `rapiq` as a whole.

When making an empty request (say, GET /users without any query params), Express sets `req.query` as `{}` by default. Usually, when making a request without customizing it with parameters, it means we'll just assume whatever default the server might have preconfigured. But who/where should we define this defaults? Is it one of the goals of this library? I think `rapiq` has all the potential to do so! But for that to work, I also consider it should work out of the box for the most popular use cases, like handling Express' empty `req.query`. Other libraries, namely Koa and Fastify, also set `req.query` as an empty object by default.

With the current behavior, undefined query parameters skip parsing, and defining them as empty lists forces parsing. But what does it really mean to have an empty list?
```typescript
const emptyInput: ParseInput = {
  fields: [],
  filters: [],
  relations: [],
  sort: [],
};
```
For filters, relations, and sort it might be clear: we want an unfiltered query, no relations, and we don't care about the order. But for the fields, an empty list might mean we want a response with no fields, but that doesn't make much sense. The current behavior results in the intersection of allows and default if both are defined, the union if only one is defined, and all fields if none are.

So, in short, I think the parameter should parse if either `allows` or `default` is defined. And if default is not defined, it should be set to `allows`. Again, if I pass an empty object and I configure the parser to have some predefined allowed values (even if there's no default), I would expect the query to be limited to those "allowed" values.

I might be wrong for the rest of the parameters, but that would mean an empty input `{}` should have the same behavior as the object with empty arrays, and maybe rethinking the meaning of an empty array, specifically for the `fields` property. This might of course break any kind of backwards compatibility for those edge cases, so I apologize if what I'm proposing seems to stray too much from `rapiq`'s original use case.

I tested some edge cases in the same [CodeSandbox](https://codesandbox.io/p/sandbox/odxclc), and added some comments describing the actual output vs what I would expect (of course, the expect part is nothing more that my personal feeling as a user of this tool, opinions might differ). Here's the code:

```typescript
import { ParseInput, ParseOptions, parseQuery } from "rapiq";

class Pet {
  name: string;
  species: string;
}

class User {
  firstName: string;
  lastName: string;
  password: string;
  age: number;
  birthDate: Date;
  pet: Pet;
}

const emptyObject: ParseInput = {};

// What does this mean by the way? A field-less query does not really makes sense
// But at the same time should this mean we want to get all the filters?
const emptyInput: ParseInput = {
  fields: [],
  filters: [],
  relations: [],
  sort: [],
};

const parsedEmptyObjectAndEmptyOptions = parseQuery<User>(emptyObject, {});
console.log(
  "parsedEmptyObjectAndEmptyOptions",
  parsedEmptyObjectAndEmptyOptions
);
// result:
// {}
// expected
// {}

const parsedEmptyObjectAndNoOptions = parseQuery<User>({});
console.log("parsedEmptyObjectAndNoOptions", parsedEmptyObjectAndNoOptions);
// result:
// {}
// expected
// {}

const parsedEmptyObjectAndNoAllowedFields = parseQuery<User>(
  {},
  {
    fields: {
      allowed: [], // should this be allowed? A query like this should make sense.
    },
  }
);
console.log(
  "parsedEmptyObjectAndNoAllowedFields",
  parsedEmptyObjectAndNoAllowedFields
);
// result:
// {}
// expected
// ?? Error maybe? Or just return all the fields of the entity.

const parsedEmptyObjectAndAllowedFields = parseQuery<User>(
  {},
  {
    fields: {
      allowed: ["firstName", "lastName"],
    },
  }
);
console.log(
  "parsedEmptyObjectAndAllowedFields",
  parsedEmptyObjectAndAllowedFields
);
// result:
// {}
// expected
// {
//   fields: [
//     { key: "firstName", path: "user" },
//     { key: "lastName", path: "user" },
//   ];
// }

const parsedEmptyInputAndAllowedFields = parseQuery<User>(emptyInput, {
  fields: {
    allowed: ["firstName", "lastName"],
  },
});
console.log(
  "parsedEmptyInputAndAllowedFields",
  parsedEmptyInputAndAllowedFields
);
// result:
// {
//   fields: [
//     { key: "firstName", path: "user" },
//     { key: "lastName", path: "user" },
//   ];
// }
// expected
// ?? it depends really, what's the meaning of an empty list in the first place?

const parsedNotAllowedFieldsAndAllowedFields = parseQuery<User>(
  {
    fields: ["password"],
  },
  {
    fields: {
      allowed: ["firstName", "lastName"],
    },
  }
);
console.log(
  "parsedNotAllowedFieldsAndAllowedFields",
  parsedNotAllowedFieldsAndAllowedFields
);
// result:
// {
//   fields: [
//     { key: "firstName", path: "user" },
//     { key: "lastName", path: "user" },
//   ];
// }
// expected
// ?? Error maybe?

const parsedEmptyObjectAndDefaults = parseQuery<User>(emptyObject, {
  fields: {
    default: ["firstName", "age"],
  },
});
console.log("parsedEmptyObjectAndDefaults", parsedEmptyObjectAndDefaults);
// result:
// {}
// expected
// {
//   relations: [],
//   fields: [ { key: 'firstName' }, { key: 'age' } ],
//   filters: [],
//   sort: []
// }

const parsedEmptyInputAndDefaults = parseQuery<User>(emptyInput, {
  fields: {
    default: ["firstName", "age"],
  },
});
console.log("parsedEmptyInputAndDefaults", parsedEmptyInputAndDefaults);
// result:
// {
//   relations: [],
//   fields: [ { key: 'firstName' }, { key: 'age' } ],
//   filters: [],
//   sort: []
// }
// expected
// ??

const parsedEmptyObjectAndAllowedWithDefaults = parseQuery<User>(emptyObject, {
  fields: {
    allowed: ["firstName", "lastName", "age", "birthDate"],
    default: ["firstName", "age"],
  },
});
console.log(
  "parsedEmptyObjectAndAllowedWithDefaults",
  parsedEmptyObjectAndAllowedWithDefaults
);
// result:
// {}
// expected
// {
//   relations: [],
//   fields: [ { key: 'firstName' }, { key: 'age' } ],
//   filters: [],
//   sort: []
// }

const parsedEmptyInputAndAllowedWithDefaults = parseQuery<User>(emptyInput, {
  fields: {
    allowed: ["firstName", "lastName", "age", "birthDate"],
    default: ["firstName", "age"],
    
  },
});
console.log(
  "parsedEmptyInputAndAllowedWithDefaults",
  parsedEmptyInputAndAllowedWithDefaults
);
// result:
// {
//   relations: [],
//   fields: [ { key: 'firstName' }, { key: 'age' } ],
//   filters: [],
//   sort: []
// }
// expected
// ??

```

**Comment by tada5hi** [comment]
> Hey @tada5hi 👋 Thanks for the response!
> 
> I started rethinking this issue and tinkering with the edge cases, and came to the conclusion that making a decision might depend on the objective of `rapiq` as a whole.
> 
> When making an empty request (say, GET /users without any query params), Express sets `req.query` as `{}` by default. Usually, when making a request without customizing it with parameters, it means we'll just assume whatever default the server might have preconfigured. But who/where should we define this defaults? Is it one of the goals of this library? I think `rapiq` has all the potential to do so! But for that to work, I also consider it should work out of the box for the most popular use cases, like handling Express' empty `req.query`. Other libraries, namely Koa and Fastify, also set `req.query` as an empty object by default.

i think the allowed option should only define which fields, filters, ... are valid inputs, whereas the default option should define values that are set when no valid input can be detected. This is currently but incorrectly only the case when the query parameter keys are defined, processed. Thus, as you have already noted, the default values for the various paramters ( filter, fields, ... ) should also be applied when the build input is empty.

> With the current behavior, undefined query parameters skip parsing, and defining them as empty lists forces parsing. But what does it really mean to have an empty list?

I think undefined query parameters should be parsed just as if they are not set, so the following inputs should be treated equally.

```ts
let input: ParseInput = {};

// and

input  = { fields: [], ... }
```

> ```ts
> const emptyInput: ParseInput = {
>   fields: [],
>   filters: [],
>   relations: [],
>   sort: [],
> };
> ```
> 
> For filters, relations, and sort it might be clear: we want an unfiltered query, no relations, and we don't care about the order. But for the fields, an empty list might mean we want a response with no fields, but that doesn't make much sense. The current behavior results in the intersection of allows and default if both are defined, the union if only one is defined, and all fields if none are.

I completely agree with you, but I think that also default options for sort, filter and relation should be applied if there is no or an invalid input. 

> So, in short, I think the parameter should parse if either `allows` or `default` is defined. And if default is not defined, it should be set to `allows`. Again, if I pass an empty object and I configure the parser to have some predefined allowed values (even if there's no default), I would expect the query to be limited to those "allowed" values.
> 
> I might be wrong for the rest of the parameters, but that would mean an empty input `{}` should have the same behavior as the object with empty arrays, and maybe rethinking the meaning of an empty array, specifically for the `fields` property. This might of course break any kind of backwards compatibility for those edge cases, so I apologize if what I'm proposing seems to stray too much from `rapiq`'s original use case.
> 
> I tested some edge cases in the same [CodeSandbox](https://codesandbox.io/p/sandbox/odxclc), and added some comments describing the actual output vs what I would expect (of course, the expect part is nothing more that my personal feeling as a user of this tool, opinions might differ). Here's the code:
> 
> ```ts
> import { ParseInput, ParseOptions, parseQuery } from "rapiq";
> 
> class Pet {
>   name: string;
>   species: string;
> }
> 
> class User {
>   firstName: string;
>   lastName: string;
>   password: string;
>   age: number;
>   birthDate: Date;
>   pet: Pet;
> }
> 
> const emptyObject: ParseInput = {};
> 
> // What does this mean by the way? A field-less query does not really makes sense
> // But at the same time should this mean we want to get all the filters?
> const emptyInput: ParseInput = {
>   fields: [],
>   filters: [],
>   relations: [],
>   sort: [],
> };
> 
> const parsedEmptyObjectAndEmptyOptions = parseQuery<User>(emptyObject, {});
> console.log(
>   "parsedEmptyObjectAndEmptyOptions",
>   parsedEmptyObjectAndEmptyOptions
> );
> // result:
> // {}
> // expected
> // {}
> 
> const parsedEmptyObjectAndNoOptions = parseQuery<User>({});
> console.log("parsedEmptyObjectAndNoOptions", parsedEmptyObjectAndNoOptions);
> // result:
> // {}
> // expected
> // {}
> 
> const parsedEmptyObjectAndNoAllowedFields = parseQuery<User>(
>   {},
>   {
>     fields: {
>       allowed: [], // should this be allowed? A query like this should make sense.
>     },
>   }
> );
> console.log(
>   "parsedEmptyObjectAndNoAllowedFields",
>   parsedEmptyObjectAndNoAllowedFields
> );
> // result:
> // {}
> // expected
> // ?? Error maybe? Or just return all the fields of the entity.
> 
> const parsedEmptyObjectAndAllowedFields = parseQuery<User>(
>   {},
>   {
>     fields: {
>       allowed: ["firstName", "lastName"],
>     },
>   }
> );
> console.log(
>   "parsedEmptyObjectAndAllowedFields",
>   parsedEmptyObjectAndAllowedFields
> );
> // result:
> // {}
> // expected
> // {
> //   fields: [
> //     { key: "firstName", path: "user" },
> //     { key: "lastName", path: "user" },
> //   ];
> // }
> 
> const parsedEmptyInputAndAllowedFields = parseQuery<User>(emptyInput, {
>   fields: {
>     allowed: ["firstName", "lastName"],
>   },
> });
> console.log(
>   "parsedEmptyInputAndAllowedFields",
>   parsedEmptyInputAndAllowedFields
> );
> // result:
> // {
> //   fields: [
> //     { key: "firstName", path: "user" },
> //     { key: "lastName", path: "user" },
> //   ];
> // }
> // expected
> // ?? it depends really, what's the meaning of an empty list in the first place?
> 
> const parsedNotAllowedFieldsAndAllowedFields = parseQuery<User>(
>   {
>     fields: ["password"],
>   },
>   {
>     fields: {
>       allowed: ["firstName", "lastName"],
>     },
>   }
> );
> console.log(
>   "parsedNotAllowedFieldsAndAllowedFields",
>   parsedNotAllowedFieldsAndAllowedFields
> );
> // result:
> // {
> //   fields: [
> //     { key: "firstName", path: "user" },
> //     { key: "lastName", path: "user" },
> //   ];
> // }
> // expected
> // ?? Error maybe?
> 
> const parsedEmptyObjectAndDefaults = parseQuery<User>(emptyObject, {
>   fields: {
>     default: ["firstName", "age"],
>   },
> });
> console.log("parsedEmptyObjectAndDefaults", parsedEmptyObjectAndDefaults);
> // result:
> // {}
> // expected
> // {
> //   relations: [],
> //   fields: [ { key: 'firstName' }, { key: 'age' } ],
> //   filters: [],
> //   sort: []
> // }
> 
> const parsedEmptyInputAndDefaults = parseQuery<User>(emptyInput, {
>   fields: {
>     default: ["firstName", "age"],
>   },
> });
> console.log("parsedEmptyInputAndDefaults", parsedEmptyInputAndDefaults);
> // result:
> // {
> //   relations: [],
> //   fields: [ { key: 'firstName' }, { key: 'age' } ],
> //   filters: [],
> //   sort: []
> // }
> // expected
> // ??
> 
> const parsedEmptyObjectAndAllowedWithDefaults = parseQuery<User>(emptyObject, {
>   fields: {
>     allowed: ["firstName", "lastName", "age", "birthDate"],
>     default: ["firstName", "age"],
>   },
> });
> console.log(
>   "parsedEmptyObjectAndAllowedWithDefaults",
>   parsedEmptyObjectAndAllowedWithDefaults
> );
> // result:
> // {}
> // expected
> // {
> //   relations: [],
> //   fields: [ { key: 'firstName' }, { key: 'age' } ],
> //   filters: [],
> //   sort: []
> // }
> 
> const parsedEmptyInputAndAllowedWithDefaults = parseQuery<User>(emptyInput, {
>   fields: {
>     allowed: ["firstName", "lastName", "age", "birthDate"],
>     default: ["firstName", "age"],
>     
>   },
> });
> console.log(
>   "parsedEmptyInputAndAllowedWithDefaults",
>   parsedEmptyInputAndAllowedWithDefaults
> );
> // result:
> // {
> //   relations: [],
> //   fields: [ { key: 'firstName' }, { key: 'age' } ],
> //   filters: [],
> //   sort: []
> // }
> // expected
> // ??
> ```

**Comment by MatiasDuhalde** [comment]
Glad we agree! That would cover my use case and the original issue, so thanks :+1: 

However, I think I'll have to backpedal about what I said here :sweat_smile: :
> I might be wrong for the rest of the parameters, but that would mean an empty input {} should have the same behavior as the object with empty arrays

Putting more thought into it, the object `{ fields: [] }`, instead of seeing it as an 'empty' fields input, we could consider it as an invalid value (since a query with no fields doesn't make much sense, as I noted before), and as you proposed, I totally agree with deferring to the default. However, for the rest of the input parameters, treating `[]` equally as `undefined` may limit some desired functionality, specially in the `filters` property.

An example : let's say we have an endpoint that queries for "pets", and we set the default filter to only return the pets where `species == "dog"`. What if the user wants to get all the pets? Testing a bit we currently have:
```typescript
const parsedEmptyArrayAndDogFilter = parseQuery<Pet>(
  {
    filters: [],
  },
  {
    filters: {
      default: { species: "dog" },
    },
  }
);
console.log(parsedEmptyArrayAndDogFilter);
// result
// { filters: [ { key: 'species', value: 'dog', operator: '$eq' } ] }
// expected
// {}

const parsedEmptyObjectAndDogFilter = parseQuery<Pet>(
  {},
  {
    filters: {
      default: { species: "dog" },
    },
  }
);
console.log(parsedEmptyObjectAndDogFilter);
// result
// {}
// expected
// { filters: [ { key: 'species', value: 'dog', operator: '$eq' } ] }
```

The behavior seems to be "flipped" :smile: If we parse `filters` even if its `undefined`, we'd eliminate the possibility of making a query with no filters. Allowing `{ filters: [] }` to be parsed as a query with no filters seems like an intuitive way to solve this problem.

So, taking that into account, yeah, I was wrong when I suggested that an empty input `{}` should have the same behavior as the object with empty arrays :sweat_smile: .

> I completely agree with you, but I think that also default options for sort, filter and relation should be applied if there is no or an invalid input.

Also, I'm steering a bit away from the subject of this issue, but users of the library might be interested in knowing whether the parsing took the defaults because the input was empty or if it was caused by an invalid input (so afterwards we have the possibility to handle it and returning a 400 or 422 status if the query turned out to be invalid). Maybe adding a `throwOnError` or `throwOnInvalid` configuration setting might be a good option? :thinking:

**Comment by tada5hi** [comment]
could you create a separater issue for the `throwOnError` option ?

**Comment by tada5hi** [comment]
https://github.com/tada5hi/rapiq/commit/c4ba3036da2b4c5bbd02411f8f54787bc7e90953

**Comment by MatiasDuhalde** [comment]
Amazing! Thank you!
