### ISSUE TITLE
Feature: Give feedback (e.g. error) if the input to parseQuery contains invalid values.

### ISSUE THREAD

**Issue by MatiasDuhalde** [tada5hi/rapiq#290]
### Is your feature request related to a problem? Please describe.

This feature proposal comes from the discussion in #261 .

### Describe the solution you'd like

Currently, if the `parseQuery` function receives invalid values in its input, like a malformed filter or trying to select a not-allowed field, the output simply ignores the value or falls back to the configured default (specific behavior is discussed partially in issue #261 ). Thus, there is no way to know with the result of the parsing operation whether the input had any errors or not.

This may lead to confusion in the users of our API, since our implementation will receive a valid output after the parsing process, and return a successful response based on our local defaults, which may in turn confuse the requester, since we're ignoring or defaulting values in their input they believed to be allowed, without returning any error or feedback.

So, my initial proposal is to add an extra `throwOnError` or `throwOnInvalid` boolean property on the options object defaulting to false, that controls whether an exception should be thrown if a problem is detected in the input during the execution of `parseQuery`. This would allow doing something like this:

```typescript

// Inside an endpoint

let result: ParseOutput;
try {
    result = parseQuery(input, {
    ...
    throwOnError: true,
  });
} catch (err) {
  if (err instanceof ParseQueryError) {
    // handle error
    res.status(422);
    return res.send('Error: ', err.message);
  }
  res.status(500);
  return res.send('Internal Server Error');
}

// make use of result
...
```

In the example, detecting this error would allow communicating a potential problem with the input to the user, for example, in the form of an error code with a descriptive message.

### Describe alternatives you've considered

Currently, there is no way of knowing if the input had invalid or erroneous values, without doing an extra step of preprocessing the input, which is done by the library anyways, so no alternatives come to mind with the current API.

An alternative feature to the error could be instead adding an extra property in the parsed output, like `errors` containing an object describing the error(s) on the input that were detected during the parsing process. This would allow having a valid parsed result, and at the same time information on the potential errors, enabling the programmer to decide whether or not to accept the default based on the specific errors, instead of interrupting the parsing process with an exception.

**Comment by tada5hi** [comment]
@MatiasDuhalde In the meantime I have started to implement the feature and would be very happy to get feedback from you.
I would be interested to know explicitly whether the differentiation between different error causes also corresponds to your ideas.
Sorry that it took a while.
The implementation can be examined in the following branch: https://github.com/tada5hi/rapiq/tree/parsing

**Comment by MatiasDuhalde** [comment]
Hey @tada5hi :wave: First of all, thank you so much for your response and for the work you've put into the project :grin: As for the delays, absolutely no worries there, as the feature proposal was just a possible improvement to the library that came to mind during our previous discussion, rather than something I needed urgently.

I took a quick look at the `parsing` branch, and in my opinion the implementation of ParseError seems more than suitable to identify the cause of the error, as it would allow doing something like `err instanceof <ParseErrorSubclass>` or `err.code === ErrorCode.<code>` to differentiate (and then doing something like returning an error response in a controller, which was my original idea).

Thanks again for the update, and I'd be glad to try out the feature once I find some free time !

**Comment by tada5hi** [comment]
you're very welcome and I'm glad you like it :blush:. Then I am reassured. 

That's good to hear :relieved: . However, I am still unsure about the wording of the parameter (`throwOnError` or `throwOnFailure`) . As soon as I have made a decision, I would make a release. What would be your preferred choice?

**Comment by MatiasDuhalde** [comment]
Sounds great !

Regarding the parameter, personally I find both options quite descriptive, and I don't have a preference of one over the other. I'll leave that decision up to you :wink:
